schema_version: 1

context:
  name: node-gyp
  version: "12.3.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/${{ name }}/-/${{ name }}-${{ version }}.tgz
  sha256: d209963f2b21fd5f6fad1f6341897a98fc8fd53025da36b319b92ebd497f6379

build:
  number: 1
  skip: win

requirements:
  build:
    - nodejs
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - node-gyp --help

about:
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: Node.js native addon build tool
  homepage: https://github.com/nodejs/node-gyp

extra:
  recipe-maintainers:
    - xhochy
